### ISSUE TITLE
[Feature Request] Add a class to Spotify modal buttons

### ISSUE THREAD

**Issue by Kanin** [powercord-org/powercord#204]
**Describe the feature request**
Add a class to the Spotify modal buttons to represent the state of them

**What Plugin would it be for?**
Spotify Modal

**Expected behavior**
Button = class = ez to theme

**Comment by TheCyberRonin** [comment]
To better describe the expected behavior and feature request:
Adding classes to the modal buttons that have states to indicate if they are on/off if they use state changes to change colors.
For instance `shuffle-on` class added to the shuffle button when it's enabled so theming can be a bit easier.

**Comment by cyyynthia** [comment]
~~Couldn't current font awesome icon class be used? Those classes are applied to the button itself (fa-play, fa-pause, fa-sync, and so on). Pure classes dedicated to that would be cleaner anyway tho~~

edit: as pointed out on discord classes may not vary for some states so that'd require use of [style*=] and that's gross
