### ISSUE TITLE
[Bug] Top of change log panel clipping on smaller screens

### ISSUE THREAD

**Issue by vinceh121** [powercord-org/powercord#249]
**Describe the bug**
On smaller screens, the titlebar of the changelog panel will be out of the screen.

**To Reproduce**
 - Have a small laptop screen from 2015
 - Open Discord with outdated Powercord
 - Click 'Update and reload'

**Expected behavior**
Title bar of changelog panel should be visible.

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Discord and Powercord version: Release Channel: canary - Discord's Build Number: 48030 - Powercord's git revision: 2db7b68f4ef09ffaba3ddc820a1e9d213caa39ad@v2

**Additional context**
 - [Image](https://i.imgur.com/Hx23AC8.png)
 - Yes I scrolled up

I know it ain't a big problem but I just thought I should let you giant-screen-having guys know

**Comment by cyyynthia** [comment]
Sadly this is a Discord issue, and since we try to reuse as much components as possible to reduce the amount of work required and increase theme compatibility, that bugs also affects Powercord. There's not a lot we can do about it, but you should report that to Discord as they might want to fix that issue that also hits people that don't use Discord maximized for any reason.

![image](https://user-images.githubusercontent.com/9999055/67621814-f543e000-f802-11e9-8310-6140ec88af27.png)
