### ISSUE TITLE
[Feature Request] Auto Unzip themes and Plugins Zips

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#303]
**Describe the feature request**
Powercord should automatically unzip zip files placed in the themes and plugins directories.

**What Plugin would it be for?**
None.

**Expected behavior**
When a user places a zip file into their plugins or themes folder(s) Powercord will automatically extract the zip file and delete it to make theme and plugin distribution as easy as dragging a zip file.

**Comment by cyyynthia** [comment]
We won't be implementing such feature, as plugin distribution through zip files is not recommended and people should always use a Git repository to ensure the flow of stability and security updates of a plugin.

**Comment by ghost** [comment]
The Git repository should be added to the manifest file, this way Powercord knows where to pull from.

**Comment by ghostlydilemma** [comment]
Git handles that on its own, why should it be put into the manifest yet again?

**Comment by cyyynthia** [comment]
Plus it'd break everything at the initialization of the git repository locally.

**Comment by ghost** [comment]
What about themes? This shouldn't be an issue with themes?

**Comment by intrnl** [comment]
Plugins and themes are handled the same way so it would still break.

**Comment by ghostlydilemma** [comment]
What do you even expect from using zips? 
If you try to get ease of installation nailed, that isn't a goal of Powercord. You are free to add that to your own fork if this is what you are trying to achieve.
Additionally the store will be a thing one day, so adding this now would just add a lot of clunky code to the codebase.

**Comment by cyyynthia** [comment]
Installing from zip files is not something we will support, period. There are a lot of issues that comes with it and themes are still subject to relatively large breakage making the client unusable and requiring an update.

And if you plan on using a simple css file to import you're really just using 2 files, which are manifest and a 1-line css file in a way we don't recommend, you except us to add a lot of code to handle it?

Windows has built-in zip files support so **installation is already a simple drag and drop**. I don't know about MacOS and if you're on a GNU/Linux and don't know how to efficiently unzip files or struggle because of it you should just stop using such OSes because you don't know how to use them.
