### ISSUE TITLE
Sass compilation fails with _index.scss directory imports

### ISSUE THREAD

**Issue by dperolio** [powercord-org/powercord#331]
**Describe the bug**
An error during Sass compilation:
```
Uncaught (in promise) Error: Can't find stylesheet to import.
  ╷
  │ @use 'pie';
  │ ^^^^^^^^^^
  ╵
```
It happens with both `@use` and `@import`.

**To Reproduce**
Make a plugin and include the file structure:
```scss
scss /
    style.scss
    pie /
        _core.scss
        _index.scss
```
`_index.scss` has `@forward 'core';` and `style.scss` has `@use 'pie';`

**Expected behavior**
It should compile the Sass just fine.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Powercord version: 023e0f6

**Additional context**
 - [ x ] I checked if Discord and/or Powercord are up to date
 - [ x ] I made sure this is not related to an external plugin or a theme

**Comment by Bowser65** [comment]
Cannot reproduce. This case is already [unit tested](https://github.com/powercord-org/powercord/blob/v2/test/scss.test.js#L95-L99) and the test is green even after reproducing your exact case.

**Comment by dperolio** [comment]
Yeah, just tried a fresh install again and still getting the compilation error. You're sure you've tested it since yesterday right? Because it worked fine prior to yesterday's compiler update.

**Comment by dperolio** [comment]
I don't really know what that means. No need to get passive aggressive, I'm just trying to help you out. I've found a couple of other users willing to try it out, and they have gotten the exact same results as me:
https://i.imgur.com/SkmO6NC.png
https://i.imgur.com/jaY96T0.png

Here is the test case plugin:
[scss-testing.zip](https://github.com/powercord-org/powercord/files/4697542/scss-testing.zip)

**Comment by Bowser65** [comment]
if you dont know what it means let me do elementary-level stuff
green = good
red = bad
unit test = test

"the unit test is green" => test good
now pls stop spam my inbox im waiting on an important email from the uni

**Comment by Gibbu** [comment]
Yeah nah aye, I get the same issue.

![screenshot](https://i.imgur.com/Zav7mZA.jpg)

**Comment by Bowser65** [comment]
![image](https://user-images.githubusercontent.com/9999055/83356643-bca35080-a367-11ea-86ed-78008abd4670.png)

**Comment by Bowser65** [comment]
Baked, I know I shouldn't give you any attention but I guess you won for this issue. Let's clarify things once and for all. In public. No hiding this time.

You have been a severe annoyance for Powercord since the very early days. You've tried to get your poorly made theme baked into Powercord because it "could being us more stars than we'd ever get". We are now over 200 stars and 3000 registered users, yet I don't hear anything about your poor excuse of a theme.

You've insulted aetheryx, said shit on Powercord and now you're sucking our dicks for yet another poor excuse of a piece of software? According to my standards that's hypocrisy and I hate it.

Your thing not a client mod and it'll never be such. It's a Powercord fork that claims to "remove bloat" while adding 10x more and adding useless crap completely against Powercord's spirit and original features targets. You don't understand a third of what you're doing and constantly asks everyone for spoon-feeding. This is not your fork, it's a fork made by the people who has the patience to endure this.

You are the combination of an attention whore and talk/act like a pedophile for your age. You are creepy and trying to do friend-friend and manipulate staff members. This is unacceptable. You are even dumb enough to directly inform a staff member you're banned but it doesn't matter because you have multiple alts in this server. It'd just inform you that this is against Discord's Terms of Service (more specifically Community Guidelines).

![image](https://user-images.githubusercontent.com/9999055/83356864-207a4900-a369-11ea-974c-8126907113d4.png)
![image](https://user-images.githubusercontent.com/9999055/83356924-8666d080-a369-11ea-97cb-18e36b381e9e.png)
*"little heated" means a chain of insults that very unfortunately got deleted (:*
![image](https://user-images.githubusercontent.com/9999055/83356888-59b2b900-a369-11ea-813a-da8a0d6f7d70.png)
And it seems you did not think any of the words you said to me when you said you didn't really know why and had your favorite target in mind
![image](https://user-images.githubusercontent.com/9999055/83357036-24f33180-a36a-11ea-889f-34e7effa7006.png)

If you want to build a client mod, then I wish you luck and hope you'll succeed. Same if you're doing a theme or a plugin. But you are not. The difference between you and me is that I am a client modder, and you are a copycat. Good luck maintaining your friends' Powercord fork.

\- Bowser
