### ISSUE TITLE
Channel notice for SDK (ex. CTRL+K channel notice)

### ISSUE THREAD

**Issue by resucutie** [powercord-org/powercord#343]
**Describe the feature request**
In pc-SDK, you can spawn the Channel Notice elements (like CTRL+K)

**What Plugin would it be for?**
pc-sdk

**Expected behavior**
You open pc-sdk window and press a button that appears channel notices. Same as +30 notification but instead of it, its the channel notice

_(btw sry for my bad engrish)_

**Comment by cyyynthia** [comment]
Since you seem to not be able to read, we do not accept any bug report or feedback for features locked under Powercord Labs. Those features are experimental and under heavy development, I only added a UI to enable them to let curious people have fun, don't make me regret switching from a hard coded lock for those.
