### ISSUE TITLE
Index.js Flagged as Trojan

### ISSUE THREAD

**Issue by dhanrahl** [powercord-org/powercord#365]
**Describe the bug**
Anti-Virus (Kaspersky), is flagging `/powercord-org/powercord/v2/src/patcher/index.js` as HEUR:Trojan.Script.Generic

In addition deletes the file on program launch despite creating the .js manually.

First encounter of this, adding an exclusion rule for now so it's available to run.

**Desktop (please complete the following information):**
 - OS: 10 v1909 Build: 18363.959
 - Powercord version: Previous and Latest Versions, git-cloned a fresh copy minutes ago.
 - Kaspersky Database Date: 7/21/2020 10:04am

**Comment by cyyynthia** [comment]
While there's not much we can do on our side, I've confirmed that two antivirus engines are flagging our patcher as harmful (Kaspersky, and ZoneAlarm). I'll get in touch with them to report this false positive, but we can't do miracles on our end. I've tried to reorganize some stuff within the file without success.

Since viruses using Discord as an entry point are spreading out, it's likely those two added an aggressive checking flagging our injector or a malware was using the same injection method. Anyway, I'll get in touch to sort this out.

**Comment by dhanrahl** [comment]
It is what it is, AV DBs always are a pain one way or another. Goal was to at least bring this to your attention as I hadn't seen any mention of it before in case others encountered it as well. 

Will mark as closed as it's an outside variable. Keep up the good work.

**Comment by cyyynthia** [comment]
Good news: I've heard back from Kaspersky team, and their malware analysis team are working on it. It should be solved soon.
