### ISSUE TITLE
[Unrelated to Code] Discord Invite Invalid

### ISSUE THREAD

**Issue by RinLovesYou** [powercord-org/powercord#390]
Didn't know where else to ask, but [this](https://discord.com/invite/5eSH46g) invite seems to be invalid. I was hoping to get some plugins/themes outside of the ones i brought over from BD.

**Comment by cyyynthia** [comment]
We are aware. One of the staff' account has been compromized and the server has been p much destroyed. We still haven't fully recovered, and all the listings are gone, so it'll take a bit for them to populate again. We're working on it.

In the meantime you can give a look to the powercord-community org where there's already some plugins, although be careful when browsing as some plugins might be unmaintained. Here's a working invite to the support server: https://discord.gg/nFRHhDk

I'll close this issue once we've changed the references within the client, as a lot of them are broken as well due to the channels being deleted.

**Comment by RinLovesYou** [comment]
Oh man that sucks, sorry to hear about that. I know how annoying it is to deal with raids. Good luck with setting everything up again!
