### ISSUE TITLE
require`powercord` resulting in error

### ISSUE THREAD

**Issue by redstonekasi** [powercord-org/powercord#396]
**Describe the bug & reproduction**
Sorry for the bad title.
When requiring like a normal person and using ``require('powercord/webpack')`` it works like normal.
When requiring like a weird person and using `` require`powercord/webpack` `` it doesn't work and say the module hasn't been found.

I guess this is because when requiring with `` require`powercord/wepback` `` it doesn't pass a string. (see images below)

**Expected behavior**
It should require the module like normal.

**Desktop (please complete the following information):**
 - OS: windows
 - Powercord version: d40440e

**Additional context**
 - [x] I made sure this is not related to an external plugin or a theme
 
 - [x] I checked if Discord and/or Powercord are up to date
 **Images**
 ![image](https://user-images.githubusercontent.com/42352565/93924260-c8e75b00-fd14-11ea-8af8-9a374c1c60d7.png)
 ![image](https://user-images.githubusercontent.com/42352565/93924306-db619480-fd14-11ea-8205-a13b30f4c5d0.png)

_i don't mind this issue being closed because literally nobody cares about something like that_

**Comment by cyyynthia** [comment]
I'll close this as a non issue; such weird syntax shouldn't be used and doesn't even seem to work on node v14.4.0 for me. Also, plugins & devtools don't share the same require; plugins use the plain Node's `require` as devtools use a custom one which was introduced to compensate for the lack of nodeIntegration due to security concerns.

**Comment by redstonekasi** [comment]
understandable
