### ISSUE TITLE
Better Codeblocks displays C++ as Arduino

### ISSUE THREAD

**Issue by Exonorid** [powercord-org/powercord#446]
**Describe the bug**
When viewing a codeblock using the language "c++" (cpp works as expected) with the Better Codeblocks plugin enabled, the language at the top will say "Arduino" instead of "C++"

**To Reproduce**
With the Better Codeblocks plugin enabled, send a message with a C++ codeblock, i.e.
\```c++
//Some c++
\```

**Expected behavior**
The language indicator should say "C++"

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - Powercord version: Revision fada35c

**Additional context**
 - [✓] I checked if Discord and/or Powercord are up to date
 - [✓] I made sure this is not related to an external plugin or a theme

How it looks as `c++`
![image](https://user-images.githubusercontent.com/68005704/104379329-8f667580-54e6-11eb-95c5-fc7245d59349.png)

How it looks as `cpp`
![image](https://user-images.githubusercontent.com/68005704/104379384-a0af8200-54e6-11eb-9563-425b5042cc2a.png)

**Comment by matortheeternal** [comment]
I took a look at this, and it appears this error originates in the Discord `parse` module.  It *could* be hotfixed by changing the `lang` argument from `c++` to `cpp` via a simple condition after [line 38](https://github.com/powercord-org/powercord/blob/v2/src/Powercord/plugins/pc-codeblocks/index.js#L38) in the codeblocks module, but that doesn't solve the underlying issue so much as mask it.

**Comment by cyyynthia** [comment]
That's more of an hljs issue than a Powercord issue. Discord uses a slightly outdated version of hljs (ver 10.1) which doesn't reset aliases for Arduino ([ref](https://github.com/highlightjs/highlight.js/blob/10-1-stable/src/languages/arduino.js)). Since it purely extends it and it comes first alphabetically, it takes priority over cpp.

While fixing it should be fairly easy (would just need to change the aliases, newer versions of hljs set `[ 'ino' ]`), what Powercord shows is actually accurate with what Discord understood: hljs will apply Arduino styling if you use `c++`.

**Comment by cyyynthia** [comment]
We've made the decision to deprecate the pc-codeblocks plugin in favor of the more feature rich [Shiki Codeblocks](https://github.com/Vap0r1ze/vpc-shiki) plugin. As such, this issue will not be fixed in pc-codeblocks and, as I mentioned, this is rather an issue within Discord than in the plugin itself which is reporting accurately what hljs understood.
