### ISSUE TITLE
[Feature Request] More Advanced Coding

### ISSUE THREAD

**Issue by DracoClaw** [powercord-org/powercord#449]
**Describe the feature request**
Auto formatting inside the chat box. Bracket balancing, and autocomplete. Maybe even the ability to define custom languages, 

**What Plugin would it be for?**
Better Codeblocks

**Expected behavior**
In the chat box, when typing out a codeblock it should automatically format your code with proper spacing, balance any brackets as well as other symbols. Based on the language specified it should suggest/autocomplete. being able to define languages not supported by discord would be very helpful as there are many that are not available, as well as allows for custom languages.

**Comment by matortheeternal** [comment]
You're basically asking to make Discord into a full-fledged code/text editor, when that is not what Discord is.  I'm not the final say on this but this seems way out of scope.  Something simple like context-aware tabs (tab character, two spaces, or four spaces) and multi-line indenting could be done fairly easily, but autocomplete, bracket balancing, custom languages, etc. are all way beyond what a chat application should offer, in my opinion.

**Comment by lavgup** [comment]
There is a request for this plugin already - https://github.com/powercord-community/suggestions/issues/178

**Comment by matortheeternal** [comment]
> There is a request for this plugin already - [powercord-community/suggestions#178](https://github.com/powercord-community/suggestions/issues/178)

I'd say they're pretty different in scope.  Even if they both address the same component that doesn't make them the same.

**Comment by lavgup** [comment]
This shouldn't be part of built-in Powercord, since many users aren't developers, and this feature will likely cause troubles that they shouldn't have to face such as increased editor lag and false positives for stripping indents of non-code blocks. Then, you decide whether you want multiple plugins to do similar/related things or one plugin to do it all.

**Comment by cyyynthia** [comment]
We've made the decision to deprecate the pc-codeblocks plugin in favor of the more feature rich [Shiki Codeblocks](https://github.com/Vap0r1ze/vpc-shiki) plugin. I'll close this issue and invite you to ask there (or to make a complete plugin requests since this is targeting the slate chat bar rather than the codeblocks themselves).
