### ISSUE TITLE
powercord does not appear to inject on manjaro (arch linux)

### ISSUE THREAD

**Issue by isXander** [powercord-org/powercord#463]
**Describe the bug**
I git pull, npm i, npm run plug etc but when I run discord canary, powercord is not there. No errors.

**To Reproduce**
`git pull blablabla`
`cd powercord`
`sudo npm i` (I need to run sudo because I am doing this in /opt)
`sudo npm run plug`
It says powercord has been successfully injected.
Open discord canary

**Expected behavior**
Powercord should work

**Desktop (please complete the following information):**
 - OS: Manjaro Linux 20.2.1 KDE Plasma (Arch Linux)
 - Powercord version: 2.0.0

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme

**Comment by old-df38257622** [comment]
It seems to work for me. Out of curiosity, can you clone to a location you have write access to and don't have to use `sudo` for `npm i`?

**Comment by Balint66** [comment]
@isXander If you have installed from aur there are two versions: discord-canary and discord-canary-electron-bin.
You should install discord-canary because powercord can not detect the other installation.

It would be nice if it could, but I wasn't able to make it work.

(by the way, the electron-bin package works like this: it compresses the resources folder into an asar file then extracts it into /usr/lib64/discord-canary and creates a script that executes the installed electron binary on that folder.)

I hope this helped. :)

**Comment by isXander** [comment]
> @isXander If you have installed from aur there are two versions: discord-canary and discord-canary-electron-bin.
> You should install discord-canary because powercord can not detect the other installation.
> 
> It would be nice if it could, but I wasn't able to make it work.
> 
> (by the way, the electron-bin package works like this: it compresses the resources folder into an asar file then extracts it into /usr/lib64/discord-canary and creates a script that executes the installed electron binary on that folder.)
> 
> I hope this helped. :)

I used discord-canary

**Comment by rosalinadev** [comment]
@isXander I had the same issue for some reason it doesn't detect where discord is installed, you should loop into `/usr/share/discord-canary` or `/usr/lib64/discord-canary` and copy the resources folder (after plugging) to where discord is installed (should be `/opt/discord-canary`).
Here are the commands if you're lazy (first one worked for me):
```
sudo cp /usr/lib64/discord-canary/resources /opt/discord-canary/
sudo cp /usr/share/discord-canary/resources /opt/discord-canary/

**Comment by cyyynthia** [comment]
Any updates on this issue?

**Comment by rosalinadev** [comment]
> Any updates on this issue?

Just tried on a fresh archlinux install with `aur/discord-canary` and `aur/powercord-git` and it worked fine. Does _not_ work when using `aur/discord-canary-electron-bin` though, which is to be expected since the commandline is electron.
Even after having the issue myself I feel like there isn't an issue here and that it's just a case of weird system installations.

**Comment by cyyynthia** [comment]
`discord-canary-electron-bin` is currently not supported by Powercord's injector, so it not working is to be expected. The person who opened the issue reported using the `discord-canary` package anyway, so it shouldn't be the cause of the problem.

I'm just checking if this person still has problems injecting as it's been almost a month since last update of this issue.

**Comment by cyyynthia** [comment]
Closing due to lack of response
