### ISSUE TITLE
[Feature Request] Put the plugins and themes directories in a sensible place

### ISSUE THREAD

**Issue by yellowsink** [powercord-org/powercord#472]
# Describe the feature request
Currently, the plugin and theme folders live in `powercord/src/Powercord/plugins` & `powercord/src/Powercord/plugins`.
This placement is unorganised and can be confusing for users who do not know what they are for.

I have been asked about removing a theme and been told that they thought these were important directories - they cause confusion.

![Evidence of confusion](https://user-images.githubusercontent.com/19270622/112767918-3bf9c300-9011-11eb-8fd5-78664741415b.png)

I propose placing them in `powercord/addons/plugins` & `powercord/addons/themes`

In addition, placing built-in plugins in with user plugins makes it incredibly easy to remove important parts of Powercord, and I think they should either be moved out of the plugins folder, or perhaps remain in their current place at `powercord/src/Powercord/plugins`.

# Expected behaviour
Plugins and themes are stored in a place that's obviously for user content, and built-in plugins aren't mixed with user plugins.

**Comment by cyyynthia** [comment]
This is something that has already been done in v3; plugins & themes (along with additional stuff like settings, cache, ...)
are stored in the following places:
  - Windows: %appdata%/powercord
  - Linux: ~/.config/powercord
  - MacOS: ~/Library/Application Support/powercord

For built-in plugins, there was some effort ongoing before we made the decision to rewrite Powercord, to move the essential ones into the "coremods" folder (which will be something done in v3 as well, since we're rewriting from the ground up anyway). Non-essentials plugins like pc-spotify, pc-hastebin, ... were planned to go away from the core since as far as late 2019.

v2 will not receive any change on that regard.

**Comment by yellowsink** [comment]
Ah ok thanks
