### ISSUE TITLE
[FEATURE] No preinstalled themes or visual plugins

### ISSUE THREAD

**Issue by kckarnige** [powercord-org/powercord#483]
**Describe the feature request**
Simply don't have any preinstalled themes or plugins on a clean install

**What Plugin would it be for?**
N/A

**Expected behavior**
On a clean install, Powercord should feel just like the official Discord client, all minor plugins and themes should be installed or at the very least, enabled by the user.

**Comment by cyyynthia** [comment]
This is something that has been planned since virtually forever (there are no preinstalled theme and there never was any), and the target for this was the release of the plugin & theme store (so people could easily get them back). It still is the target, but this is something that will happen in v3 once it's released, polished and the store is available there. v2 will keep its preinstalled, non-essential plugins

**Comment by kckarnige** [comment]
Alright, thanks for the info!
