### ISSUE TITLE
[Feature Request] Spotify controls with playerctl

### ISSUE THREAD

**Issue by ghost** [powercord-org/powercord#528]
**Describe the feature request**
On Linux, there is [playerctl](https://github.com/altdesktop/playerctl) utility, which can control playing. I think that it is possible to do spotify controls for non-premium users  in powercord with playerctl. E.g.: there is something playing in spotify. When i type `playerctl pause` in terminal, music pauses, so it works.

**What Plugin would it be for?**
Spotify

**Expected behavior**
Not applicable

**Comment by TheArcaneBrony** [comment]
Probably a wontfix due to spotify's own rules.

**Comment by cyyynthia** [comment]
v3 plans are to completely block access to OS-level APIs to plugins due to huge security issues that can arise from having such capacities. That means plugins will not be able to run an external executable, communicate with other processes though system-level pipes (unix pipes, windows' named pipes, ...), making implementing this not possible for the Spotify plugin.

We also prefer to avoid platform-specific code whenever possible.
