### ISSUE TITLE
my pop out breaks when I hit to pop out

### ISSUE THREAD

**Issue by PichuRose** [powercord-org/powercord#551]
basically, I am in a vc, and I watch a stream, and then it works perfectly fine. But when I hit the button to pop out, the window does not exist except as an icon on the task bar.

join a vc, watch a stream, and hit pop out

I expect it to open a separate window that can stay on top and I can watch

 - Windows
 - ea8c01e

 - [yes ] I checked if Discord and/or Powercord are up to date
 - [no ] I made sure this is not related to an external plugin or a theme

**Comment by cyyynthia** [comment]
Cannot reproduce on latest Discord Canary on Linux. Either it is due to a plugin you have installed that conflicts with the functionality, or it is a platform specific issue affecting Windows users.

I'll try to test on Windows later, not today though.

![image](https://user-images.githubusercontent.com/9999055/133905447-95ef7725-1ac0-496c-822f-2423bf1add73.png)

**Comment by 12944qwerty** [comment]
I've just tried on windows, it works perfectly for me.
![image](https://user-images.githubusercontent.com/45984786/133905602-d302a125-8c25-467f-87c2-2b1286c4f241.png)

**Comment by Codeize** [comment]
Also tested on Windows, cannot reproduce.

**Comment by cyyynthia** [comment]
Based on the fact 3 people (2 Windows users) can't reproduce, and without a response from the reporter I'll be closing this issue.
