### ISSUE TITLE
Crash/reload Discord A LOT

### ISSUE THREAD

**Issue by neyako** [powercord-org/powercord#577]
Like a title, sometimes it's reload **a lot** and I can't use Discord anymore...
It still happens 5-6 times if I try close and open it again

https://user-images.githubusercontent.com/64780385/141794096-1e6b4370-13ab-4491-8ecc-78ca5df1bff9.mp4

**Comment by neyako** [comment]
Plugins folder:
![image](https://user-images.githubusercontent.com/64780385/141794325-babc948f-99ec-4c78-bb8d-749f9bb4af5a.png)

~~bdCompact folder~~ Already removed it because powercord guidelines. I still have this problem after removed it.

I also installed Glasscord, already try uninstall but still.

**Comment by BenSegal855** [comment]
Maybe don't violate the [guidelines](https://powercord.dev/guidelines) if you want help.

**Comment by neyako** [comment]
Oh, I forgot MessageLogger is against guidelines. Sorry about that.

**Comment by x0rp01s0n** [comment]
The exact same happens to me as soon as i join a voicechat,
continuing to crash again because of discords auto connect.
I disabled all plugins this is not a plugin error.
im on Linux on latest powecord.
it happens right in the moment when webrtc send an ok and you get the green text in the corner.
![image](https://user-images.githubusercontent.com/43322985/143685778-74200bfe-5446-452e-90f3-3609364f4d09.png)

Edit: i somehow uninstalled a library discord needed to establish a webrtc connection and my discord isnt crashing anymore.
your crashing issue probably leads to BdCompat's loader which is conflicting with zeres plugin library.

**Comment by xamionex** [comment]
Sorry for replying on an old issue but Premid-Powercord is broken aswell and It was probably crashing you aswell

**Comment by MulverineX** [comment]
Back then it wouldn't have caused the crash, but yes it has a bug when you have a presence running and another plugin causes a crash your client will enter a crash loop.  https://github.com/MulverineX/premid-powercord/issues/6

**Comment by cyyynthia** [comment]
For support requests please join our [support server](https://discord.gg/powercord) and ask in the appropriated channel.
