### ISSUE TITLE
[Feature Request] Regulate requests to the discord API on the client side.

### ISSUE THREAD

**Issue by JoshuaVandaele** [powercord-org/powercord#604]
**Describe the feature request**
Some [people](https://github.com/powercord-org/powercord/issues/603) have concerns that Powercord, through third-party plugins, may not respect the ratelimit between them, causing a ban on Discord.
I think a solution would be checking if the API calls made to discord would violate the ratelimit or not, on a global basis.

**What Plugin would it be for?**
N/A

**Expected behavior**
If multiple different plugins make calls to the same API endpoint, we may hit a ratelimit. If it happens too often, an user may get sanctioned.
A global functionality to check if we're going to hit it and halting the request before this happens may be of help.

**Comment by cyyynthia** [comment]
It isn't feasible to track what plugins do compared to what Discord does, first because we can't distinguish both of them and because plugins may cause side effects we can't monitor. Refer to https://github.com/powercord-org/powercord/issues/386#issuecomment-707916207 for what we *already* considered and are working on.
