### ISSUE TITLE
Right click on user crashes Discord

### ISSUE THREAD

**Issue by asportnoy** [powercord-org/powercord#663]
**Describe the bug**
Title

**To Reproduce**
Title

**Expected behavior**
Not crash

**Desktop (please complete the following information):**
 - OS: macOS
 - Powercord version: 794f8c6

**Additional context**
 - [x] I checked if Discord and/or Powercord are up to date
 - [x] I made sure this is not related to an external plugin or a theme
 
~~Only occurs on Canary right now~~ Changes landed on stable too. Other people were able to reproduce.

**Comment by asportnoy** [comment]
Thanks to @12944qwerty we've narrowed the issue down to `pc-emojiUtility`

**Comment by Lordmau5** [comment]
Did some debug logging and traced it down to this particular `wrapInHooks` call:
https://github.com/powercord-org/powercord/blob/v2/src/fake_node_modules/powercord/util/injectContextMenu.js#L65

Not sure if that's helpful or you guys already know about it happening in this part of hte code, but since I'm also experiencing this I thought I'd look around a bit.

**Comment by pythonius21** [comment]
happens to me too

**Comment by Cosmiiko** [comment]
Can reproduce. Version info:
```
Canary 135383 (52cc282) 
Host 1.0.47 Windows 10 64-Bit (10.0.19044)
Powercord v2 (794f8c6)
```

Edit: Issue seemingly went away it seems...

**Comment by pythonius21** [comment]
> Edit: Issue seemingly went away it seems...

after you updated discord?
Edit: Still crashes
Canary 135468 (34b0605) 
Host 1.0.47 Windows 10 64-Bit (10.0.19044)
Powercord v2 (794f8c6)

**Comment by asportnoy** [comment]
The issue comes and goes.
